require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DocPagesController do

  # This should return the minimal set of attributes required to create a valid
  # DocPage. As you add validations to DocPage, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DocPagesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all doc_pages as @doc_pages" do
      doc_page = DocPage.create! valid_attributes
      get :index, {}, valid_session
      assigns(:doc_pages).should eq([doc_page])
    end
  end

  describe "GET show" do
    it "assigns the requested doc_page as @doc_page" do
      doc_page = DocPage.create! valid_attributes
      get :show, {:id => doc_page.to_param}, valid_session
      assigns(:doc_page).should eq(doc_page)
    end
  end

  describe "GET new" do
    it "assigns a new doc_page as @doc_page" do
      get :new, {}, valid_session
      assigns(:doc_page).should be_a_new(DocPage)
    end
  end

  describe "GET edit" do
    it "assigns the requested doc_page as @doc_page" do
      doc_page = DocPage.create! valid_attributes
      get :edit, {:id => doc_page.to_param}, valid_session
      assigns(:doc_page).should eq(doc_page)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new DocPage" do
        expect {
          post :create, {:doc_page => valid_attributes}, valid_session
        }.to change(DocPage, :count).by(1)
      end

      it "assigns a newly created doc_page as @doc_page" do
        post :create, {:doc_page => valid_attributes}, valid_session
        assigns(:doc_page).should be_a(DocPage)
        assigns(:doc_page).should be_persisted
      end

      it "redirects to the created doc_page" do
        post :create, {:doc_page => valid_attributes}, valid_session
        response.should redirect_to(DocPage.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved doc_page as @doc_page" do
        # Trigger the behavior that occurs when invalid params are submitted
        DocPage.any_instance.stub(:save).and_return(false)
        post :create, {:doc_page => {  }}, valid_session
        assigns(:doc_page).should be_a_new(DocPage)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        DocPage.any_instance.stub(:save).and_return(false)
        post :create, {:doc_page => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested doc_page" do
        doc_page = DocPage.create! valid_attributes
        # Assuming there are no other doc_pages in the database, this
        # specifies that the DocPage created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        DocPage.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => doc_page.to_param, :doc_page => { "these" => "params" }}, valid_session
      end

      it "assigns the requested doc_page as @doc_page" do
        doc_page = DocPage.create! valid_attributes
        put :update, {:id => doc_page.to_param, :doc_page => valid_attributes}, valid_session
        assigns(:doc_page).should eq(doc_page)
      end

      it "redirects to the doc_page" do
        doc_page = DocPage.create! valid_attributes
        put :update, {:id => doc_page.to_param, :doc_page => valid_attributes}, valid_session
        response.should redirect_to(doc_page)
      end
    end

    describe "with invalid params" do
      it "assigns the doc_page as @doc_page" do
        doc_page = DocPage.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DocPage.any_instance.stub(:save).and_return(false)
        put :update, {:id => doc_page.to_param, :doc_page => {  }}, valid_session
        assigns(:doc_page).should eq(doc_page)
      end

      it "re-renders the 'edit' template" do
        doc_page = DocPage.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DocPage.any_instance.stub(:save).and_return(false)
        put :update, {:id => doc_page.to_param, :doc_page => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested doc_page" do
      doc_page = DocPage.create! valid_attributes
      expect {
        delete :destroy, {:id => doc_page.to_param}, valid_session
      }.to change(DocPage, :count).by(-1)
    end

    it "redirects to the doc_pages list" do
      doc_page = DocPage.create! valid_attributes
      delete :destroy, {:id => doc_page.to_param}, valid_session
      response.should redirect_to(doc_pages_url)
    end
  end

end
