require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FilingsController do

  # This should return the minimal set of attributes required to create a valid
  # Filing. As you add validations to Filing, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FilingsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all filings as @filings" do
      filing = Filing.create! valid_attributes
      get :index, {}, valid_session
      assigns(:filings).should eq([filing])
    end
  end

  describe "GET show" do
    it "assigns the requested filing as @filing" do
      filing = Filing.create! valid_attributes
      get :show, {:id => filing.to_param}, valid_session
      assigns(:filing).should eq(filing)
    end
  end

  describe "GET new" do
    it "assigns a new filing as @filing" do
      get :new, {}, valid_session
      assigns(:filing).should be_a_new(Filing)
    end
  end

  describe "GET edit" do
    it "assigns the requested filing as @filing" do
      filing = Filing.create! valid_attributes
      get :edit, {:id => filing.to_param}, valid_session
      assigns(:filing).should eq(filing)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Filing" do
        expect {
          post :create, {:filing => valid_attributes}, valid_session
        }.to change(Filing, :count).by(1)
      end

      it "assigns a newly created filing as @filing" do
        post :create, {:filing => valid_attributes}, valid_session
        assigns(:filing).should be_a(Filing)
        assigns(:filing).should be_persisted
      end

      it "redirects to the created filing" do
        post :create, {:filing => valid_attributes}, valid_session
        response.should redirect_to(Filing.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved filing as @filing" do
        # Trigger the behavior that occurs when invalid params are submitted
        Filing.any_instance.stub(:save).and_return(false)
        post :create, {:filing => {  }}, valid_session
        assigns(:filing).should be_a_new(Filing)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Filing.any_instance.stub(:save).and_return(false)
        post :create, {:filing => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested filing" do
        filing = Filing.create! valid_attributes
        # Assuming there are no other filings in the database, this
        # specifies that the Filing created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Filing.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => filing.to_param, :filing => { "these" => "params" }}, valid_session
      end

      it "assigns the requested filing as @filing" do
        filing = Filing.create! valid_attributes
        put :update, {:id => filing.to_param, :filing => valid_attributes}, valid_session
        assigns(:filing).should eq(filing)
      end

      it "redirects to the filing" do
        filing = Filing.create! valid_attributes
        put :update, {:id => filing.to_param, :filing => valid_attributes}, valid_session
        response.should redirect_to(filing)
      end
    end

    describe "with invalid params" do
      it "assigns the filing as @filing" do
        filing = Filing.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Filing.any_instance.stub(:save).and_return(false)
        put :update, {:id => filing.to_param, :filing => {  }}, valid_session
        assigns(:filing).should eq(filing)
      end

      it "re-renders the 'edit' template" do
        filing = Filing.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Filing.any_instance.stub(:save).and_return(false)
        put :update, {:id => filing.to_param, :filing => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested filing" do
      filing = Filing.create! valid_attributes
      expect {
        delete :destroy, {:id => filing.to_param}, valid_session
      }.to change(Filing, :count).by(-1)
    end

    it "redirects to the filings list" do
      filing = Filing.create! valid_attributes
      delete :destroy, {:id => filing.to_param}, valid_session
      response.should redirect_to(filings_url)
    end
  end

end
