require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ProceedingsController do

  # This should return the minimal set of attributes required to create a valid
  # Proceeding. As you add validations to Proceeding, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ProceedingsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all proceedings as @proceedings" do
      proceeding = Proceeding.create! valid_attributes
      get :index, {}, valid_session
      assigns(:proceedings).should eq([proceeding])
    end
  end

  describe "GET show" do
    it "assigns the requested proceeding as @proceeding" do
      proceeding = Proceeding.create! valid_attributes
      get :show, {:id => proceeding.to_param}, valid_session
      assigns(:proceeding).should eq(proceeding)
    end
  end

  describe "GET new" do
    it "assigns a new proceeding as @proceeding" do
      get :new, {}, valid_session
      assigns(:proceeding).should be_a_new(Proceeding)
    end
  end

  describe "GET edit" do
    it "assigns the requested proceeding as @proceeding" do
      proceeding = Proceeding.create! valid_attributes
      get :edit, {:id => proceeding.to_param}, valid_session
      assigns(:proceeding).should eq(proceeding)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Proceeding" do
        expect {
          post :create, {:proceeding => valid_attributes}, valid_session
        }.to change(Proceeding, :count).by(1)
      end

      it "assigns a newly created proceeding as @proceeding" do
        post :create, {:proceeding => valid_attributes}, valid_session
        assigns(:proceeding).should be_a(Proceeding)
        assigns(:proceeding).should be_persisted
      end

      it "redirects to the created proceeding" do
        post :create, {:proceeding => valid_attributes}, valid_session
        response.should redirect_to(Proceeding.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved proceeding as @proceeding" do
        # Trigger the behavior that occurs when invalid params are submitted
        Proceeding.any_instance.stub(:save).and_return(false)
        post :create, {:proceeding => {  }}, valid_session
        assigns(:proceeding).should be_a_new(Proceeding)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Proceeding.any_instance.stub(:save).and_return(false)
        post :create, {:proceeding => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested proceeding" do
        proceeding = Proceeding.create! valid_attributes
        # Assuming there are no other proceedings in the database, this
        # specifies that the Proceeding created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Proceeding.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => proceeding.to_param, :proceeding => { "these" => "params" }}, valid_session
      end

      it "assigns the requested proceeding as @proceeding" do
        proceeding = Proceeding.create! valid_attributes
        put :update, {:id => proceeding.to_param, :proceeding => valid_attributes}, valid_session
        assigns(:proceeding).should eq(proceeding)
      end

      it "redirects to the proceeding" do
        proceeding = Proceeding.create! valid_attributes
        put :update, {:id => proceeding.to_param, :proceeding => valid_attributes}, valid_session
        response.should redirect_to(proceeding)
      end
    end

    describe "with invalid params" do
      it "assigns the proceeding as @proceeding" do
        proceeding = Proceeding.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Proceeding.any_instance.stub(:save).and_return(false)
        put :update, {:id => proceeding.to_param, :proceeding => {  }}, valid_session
        assigns(:proceeding).should eq(proceeding)
      end

      it "re-renders the 'edit' template" do
        proceeding = Proceeding.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Proceeding.any_instance.stub(:save).and_return(false)
        put :update, {:id => proceeding.to_param, :proceeding => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested proceeding" do
      proceeding = Proceeding.create! valid_attributes
      expect {
        delete :destroy, {:id => proceeding.to_param}, valid_session
      }.to change(Proceeding, :count).by(-1)
    end

    it "redirects to the proceedings list" do
      proceeding = Proceeding.create! valid_attributes
      delete :destroy, {:id => proceeding.to_param}, valid_session
      response.should redirect_to(proceedings_url)
    end
  end

end
